name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format-biblioteca-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run formatter
        working-directory: ./biblioteca_backend
        run: cargo fmt
      - name: Run clippy
        working-directory: ./biblioteca_backend
        run: cargo clippy --all-targets --all-features -- -D warnings
  test-biblioteca-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build la-biblioteca backend
      working-directory: ./biblioteca_backend
      run: cargo build
    - name: Run tests
      working-directory: ./biblioteca_backend
      run: cargo test