name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build la-biblioteca backend
      working-directory: ./biblioteca_backend
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./biblioteca_backend
      run: cargo test --verbose && rm *.sqlite
    - name: Run formatter
      working-directory: ./biblioteca_backend
      run: cargo format
    - name: Run clippy
      working-directory: ./biblioteca_backend
      run: cargo clippy